# Generated by Django 5.0.4 on 2024-05-02 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='last_modified',
        ),
    ]
