# Generated by Django 5.0.4 on 2024-05-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_remove_blog_date_created_remove_blog_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
